package com.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import ys.app.petproject.widgetprovider.AppWidgetIdInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "APP_WIDGET_ID_INFO".
*/
public class AppWidgetIdInfoDao extends AbstractDao<AppWidgetIdInfo, Long> {

    public static final String TABLENAME = "APP_WIDGET_ID_INFO";

    /**
     * Properties of entity AppWidgetIdInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property AppWidgetId = new Property(1, String.class, "appWidgetId", false, "APP_WIDGET_ID");
    }


    public AppWidgetIdInfoDao(DaoConfig config) {
        super(config);
    }
    
    public AppWidgetIdInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"APP_WIDGET_ID_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"APP_WIDGET_ID\" TEXT);"); // 1: appWidgetId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"APP_WIDGET_ID_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, AppWidgetIdInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String appWidgetId = entity.getAppWidgetId();
        if (appWidgetId != null) {
            stmt.bindString(2, appWidgetId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, AppWidgetIdInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String appWidgetId = entity.getAppWidgetId();
        if (appWidgetId != null) {
            stmt.bindString(2, appWidgetId);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public AppWidgetIdInfo readEntity(Cursor cursor, int offset) {
        AppWidgetIdInfo entity = new AppWidgetIdInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // appWidgetId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, AppWidgetIdInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setAppWidgetId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(AppWidgetIdInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(AppWidgetIdInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(AppWidgetIdInfo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
